### ISSUE TITLE
Doesn't work in safari

### ISSUE THREAD

**Issue by rohitkhatri** [Maykonn/js-detect-incognito-private-browsing-paywall#1]
It's giving normal mode in Safari's Private mode.

**Comment by Maykonn** [comment]
I'm aware of it. Even though Safari 11 have a incognito/private mode, the behaviour is different from other browsers. This mode on new Safari versions is designed to avoid the detection. However, I'm looking for a solution.

**Comment by rAthur** [comment]
Came to report it as well, I don't know if _rohitkhatri_ was talking about Safari on desktop but I have the issue on Safari Mobile for sure.

**Comment by Maykonn** [comment]
@rAthur thanks by reporting it. As explained in my previous comment regarding the newest versions of Safari, for the time being, I'm not able to find a way to make the browsing mode detection. I'm working on tests to identify a possible resource that provides the possibility to identify a private or incognito browsing on Safari 11+.

**Comment by bateller** [comment]
Safari Detecting:

```
    const isSafari = navigator.userAgent.match(/Version\/([0-9\._]+).*Safari/);
    if (isSafari) {
      const version = parseInt(isSafari[1], 10);
      if (version >= 11) {
         try {
           window.openDatabase(null, null, null, null);
           return off();
         } catch (_) {
           return on();
         };
      } else if (version < 11) {
        return testLocalStorage();
      }
   }
```

From: https://gist.github.com/jherax/a81c8c132d09cc354a0e2cb911841ff1
