### ISSUE TITLE
Help to implement latest Safari & iOS detector

### ISSUE THREAD

**Issue by feelinc** [Maykonn/js-detect-incognito-private-browsing-paywall#10]
Hi,

Tested in Safari 13 and iOS 13.2

```
function tryFillLocalStorage (chunkSize) {
  var size = chunkSize / 4; // chunk will be repetition of 4B
  var content = (new Array(size+1)).join('aあ');
  var blob = {
    size:     chunkSize,
    payload:  content
  };
  // now is the generated time
  blob.lastModifiedDate = new Date();
  // Name it random so key won't conflict
  blob.name = (~~(Math.random()*100000)+100000)+'.txt';

  try {
    localStorage.setItem(blob.name, JSON.stringify(blob));
  } catch(e) {
    try {
      localStorage.removeItem(blob.name);
    } catch(e) {}

    return false;
  }

  try {
    localStorage.removeItem(blob.name);
  } catch(e) {}

  return true;
}

// normal mode having max 5 MB in localStorage space,
// yes NORMAL MODE having max 5 MB
var LOCAL_STORAGE_DATA_SIZE = 1024 * 1024 * 5; // 5MB

if (tryFillLocalStorage(LOCAL_STORAGE_DATA_SIZE)) {
  // IN PRIVATE MODE
}
```

Please if you can help implement and optimize that, because I'm currently using a whole different code structure, which support strict mode code.

Also please check [this line of code](https://github.com/Maykonn/js-detect-incognito-private-browsing-paywall/blob/71091b83d54bbb4ebb2568a9768145abe3708e56/BrowsingModeDetector.js#L291), because you have a typo there.

Thanks.

**Comment by Maykonn** [comment]
Hi, thank you for your help. [Typo fixed here](https://github.com/Maykonn/js-detect-incognito-private-browsing-paywall/commit/6837562120acb4764d952d77c772dfd9af75528e).

I already thought of keeping a strict version using ES6 (or higher), and a browser version with var, etc. I think it is possible to do using only one code script and compile it for several browser versions via webpack.

Actually I already had added a webpack support we can test it via the commands below:
`npm start` for development environments
`npm build` will compile the code for production environments (as compressing the file with gzip for example)

You can see it on the webpack files in this repository.

**Comment by Maykonn** [comment]
[The new release](https://github.com/Maykonn/js-detect-incognito-private-browsing-paywall/releases/tag/v2.5.1) launched today is up to fix any bug detected 'til now. Please, take a look at the commit history to see the fixed bugs @feelinc
