### ISSUE TITLE
Does it still work with Chrome?

### ISSUE THREAD

**Issue by robhawkins** [Maykonn/js-detect-incognito-private-browsing-paywall#11]
Does this work in Chrome 78? I just tried it for the first time and while it detects a private session in Firefox, it does not in Chrome.

I also saw a [post](https://www.bleepingcomputer.com/news/google/google-chrome-incognito-mode-can-still-be-detected-by-these-methods/) saying the following,

> When asking Google about these two new detection methods, Google has told BleepingComputer that they stand by their statement that they will "work to remedy any other current or future means of Incognito Mode detection."

By the way, it would be convenient if this could be imported like other modules. I'm not sure what the `window.BrowsingModeDetector` syntax does, though if I change it to `export function BrowsingModeDetector()...` it appears to import normally, and this is how I tested it.

**Comment by Maykonn** [comment]
@robhawkins firstly thanks. The idea of window.BrowsingModeDetector is to provide a way to add a BrowsingModeDetector to the window scope even if you are not making use of the ES6, node, webpack, etc. You can include the <script> tag in your html, hence this script could be used by the large majority of cases.

**Comment by Maykonn** [comment]
I just fixed the issues for Chrome and Firefox as well. [Get the latest release here](https://github.com/Maykonn/js-detect-incognito-private-browsing-paywall/releases/tag/v2.5.1).

**Comment by jiromesarb** [comment]
It returns "Normal browsing" on my incognito chrome Version 86.0.4240.198

**Comment by jiromesarb** [comment]
It returns "Normal browsing" on my incognito chrome Version 86.0.4240.198
