### ISSUE TITLE
False positive on Mozila Firefox 65.0.2

### ISSUE THREAD

**Issue by avramionutbogdan** [Maykonn/js-detect-incognito-private-browsing-paywall#3]
False positive private browsing on Mozila Firefox 65.0.2.
If I test the library on a localhost it works as it should but if I test it on a hosted app it always returns true (private browsing) even if the browser is in normal mode.

**Comment by daniellight** [comment]
This sounds similar to an issue I raised in October of last year.  After a certain amount of to-and-fro we were unable to resolve.  Ultimately it meant that I was unable to make use of this library.

**Comment by Maykonn** [comment]
@daniellight the issue that you referred to is: #2 

In that time I've detected that the problem occurs after some page redirects executed by the web server.
