### ISSUE TITLE
Issue with webpack

### ISSUE THREAD

**Issue by jarcos** [Maykonn/js-detect-incognito-private-browsing-paywall#5]
After installing Browsing Mode Detector library as Dev Dependency I'm getting this error on the JS Console:

`Uncaught TypeError: js_detect_incognito_private_browsing__WEBPACK_IMPORTED_MODULE_2___default.a is not a constructor
`

What I did was just, install the library using npm:

`npm i -D js-detect-incognito-private-browsing`

Then, import it as module in my index.js file:

`import BrowsingModeDetector from 'js-detect-incognito-private-browsing'`

What am I missing? Am I importing wrong the library?

**Comment by Maykonn** [comment]
@jarcos did you find how fix it?

**Comment by jarcos** [comment]
Sorry @Maykonn, I finally abandoned this project, we can close this issue if you want. Thanks for your work ;)
