### ISSUE TITLE
Store Browsing Mode in a variable

### ISSUE THREAD

**Issue by jarcos** [Maykonn/js-detect-incognito-private-browsing-paywall#6]
Hi there. I'm developing a library for handle cookies and comply with the European Laws. So, I'm using this the detect incognito library for detecting when a user is navigating on incognito mode. So, after this introduction, I'd like to know if it is possible to store the browsing mode in a variable outside the callback function. 
My code looks like:

```
var browsingModeCallback = function (browsingInIncognitoMode) {
            if (browsingInIncognitoMode && 'true' != Cookies.get( 'ez_accepted' ) ) {
                // Incognito, Private mode detected
                $( '.ez-waiting-img' ).hide();
                $( '.ez-waiting-message' ).hide();
                $( '.ez-waiting-optout' ).show();
                disableCookies();
                return;
            }
        };
        var BrowsingModeDetectorInstance = new BrowsingModeDetector();
        BrowsingModeDetectorInstance.do(browsingModeCallback);
```

But I need to know the value of `browsingInIncognitoMode` outside that scope. It is possible? if so, how can I do it?

Thanks.

**Comment by Maykonn** [comment]
Hi @jarcos, nice to know that the project is going to be useful for your project too. You may implement something like the code below in order to retrieve the mode that the user is browsing:

```
var BrowsingModeDetectorInstance = new BrowsingModeDetector();
BrowsingModeDetectorInstance.do(myCallback); // do() method executes the browsing mode detection
var browsingMode = BrowsingModeDetectorInstance.getBrowsingMode();
console.log('The browsing mode is: ', browsingMode);
```

The two possible values returned by the getBrowsingMode() method are: `NORMAL_MODE` and `INCOGNITO_PRIVATE_MODE`.

You can test with: 
```
var browsingMode = BrowsingModeDetectorInstance.getBrowsingMode();
if (browsingMode === BrowsingModeDetectorInstance.BROWSING_NORMAL_MODE) 
{
    // do something here...
}
```

**Comment by jarcos** [comment]
Thank you, @Maykonn. I tried that, but I'm getting confusing results. This is my code now:

       ```
 var browsingModeCallback = function (browsingInIncognitoMode, BrowsingModeDetectorInstance) {
            if (browsingInIncognitoMode && 'true' != Cookies.get( 'ez_accepted' ) ) {
                // Incognito, Private mode detected
                // $( '.ez-waiting-img' ).hide();
                // $( '.ez-waiting-message' ).hide();
                // $( '.ez-waiting-optout' ).show();
                // disableCookies();
                console.log( 'Inside the callback. The browsing mode is: ', BrowsingModeDetectorInstance.getBrowsingMode() );
                return;
            }
        };
          
        var BrowsingModeDetectorInstance = new BrowsingModeDetector();
        BrowsingModeDetectorInstance.do(browsingModeCallback);
        var browsingMode = BrowsingModeDetectorInstance.getBrowsingMode();
        console.log( 'Outside the callback. The browsing mode is: ', browsingMode );
```

It doesn't work outside the callback on Chrome, neither on Safari but it detects the Private Mode on Firefox properly. 

Am I missing something?

**Comment by Maykonn** [comment]
Actually, I've been thinking here, that it makes sense you get that wrong behavior because the `BrowsingModeDetectorInstance.getBrowsingMode();` it's being called before the `do()` method finishes its process (in reason of the javascript async nature).

I need to put more investigation time on it because what I said is a guess. I'm not sure yet.

For now, can you make use of the advanced callbacks? Something like that:
```
var callbackWhenNormalMode = function (BrowsingModeDetectorInstance) {
  console.log('It is a normal browsing?', BrowsingModeDetectorInstance.getBrowsingMode());
};

var callbackWhenIncognitoOrPrivateMode = function (BrowsingModeDetectorInstance) {
  console.log('It is a incognito browsing?', BrowsingModeDetectorInstance.getBrowsingMode());
};

var BrowsingModeDetectorInstance = new BrowsingModeDetector();
BrowsingModeDetectorInstance
  .setCallbackForNormalMode(callbackWhenNormalMode)
  .setCallbackForIncognitoOrPrivateMode(callbackWhenIncognitoOrPrivateMode)
  .do(defaultCallback);
```

**Comment by Maykonn** [comment]
@jarcos you can make use of some library like [bluebird](https://www.guru99.com/bluebird-promises.html). Thus you are able to use promises.

**Comment by jarcos** [comment]
Sorry @Maykonn, I finally abandoned this project, we can close this issue if you want. Thanks for your work ;)
